white-list-external: ["localhost", "kyma.local"]
white-list-internal: ["mailto:kyma-security@googlegroups.com"]
black-list: ["/templates/","-template.md"]
timeout: 60
request-repeats: 5
files:
  - path: "./community/.github/ISSUE_TEMPLATE/security-vulnerability.md"
    config:
      white-list-internal: ["{CVSS"]
  - path: "./community/guidelines/content-guidelines/formatting-and-style.md"
    config:
      white-list-internal: ["./deployment.yaml"]
  - path: "./community/guidelines/releases/release-process.md"
    config:
      white-list-external: ["https://github.com/kyma-project/{repositoryname}/releases"]
  - path: "./community/git-workflow.md"
    config:
      white-list-external: ["https://github.com/{your-username}/{your-fork-name}.git"]
  - path: "./community/CONTRIBUTING.md"
    config:
      #milv doesn't support parenthesis in parenthesis in .md links yet
      white-list-external: ["https://github.com/kyma-project/community/blob/master/docs/cla/SAP%20Corporate%20Contributor%20License%20Agreement%20(5-26-15"]
